@startuml
actor       "Пользователь" as User
participant "МП IYM"       as App
participant "IYM Backend"  as BE
participant "IYM Jobs"     as Jobs
participant "ISBM"         as ISBM
participant "Tieto CS"     as TCS

==Подгрузка карт==
User -> App : Открыть МП
activate User
activate App
App -> BE : Запрос на ревизию
activate BE
App <-- BE : Временная метка ревизии
BE -> BE : Проверка последней \nревизии карт
note over BE
Проверка по пользователю,
его **user_id**
end note
alt > 10 мин.
BE -> Jobs : Обновить карты \nпользователя
deactivate BE
activate Jobs
end
note over App
МП локально хранит
послед. метку
end note
App -> App : Сверка меток ревизии
alt Нет совпадения
    App -> BE : Запрос списка карт
    activate BE
    App <-- BE : Список карт
end
App -> BE : Запрос баланса карт
note over BE
Баланс всегда идет
с ПЦ, упрощенно
end note
App <-- BE : Баланс карт
deactivate BE
User <-- App : Отображение карт
deactivate App
deactivate User
==Внесение/Обновление карт==
Jobs -> ISBM : Запрос клиентов \nпользователя
activate ISBM
Jobs <-- ISBM : Клиенты пользователя
loop N клиентов
    Jobs -> ISBM : Запрос карт Tieto
    ISBM -> TCS : Запрос списка карт
    activate TCS
    ISBM <-- TCS : Список карт
    deactivate TCS
    Jobs <-- ISBM : Список карт Tieto
end
deactivate ISBM
alt Имеются обновления
    note over Jobs #SkyBlue
    IYM Jobs вносит новые карты
    и изменения в **users_cards**
    с актуальными метками
    end note
end
deactivate Jobs

@enduml
