@startmindmap
*[#lightgreen] Заявление отправлено
**[#lightgreen] Карта получена в МП
***[#lightgreen] Открыт экран КК
****[#lightgreen] Кредитный лимит получен
*****[#lightgreen] Кредитная анкета открыта
*****[#FFBBCC] Ошибка при открытии анкеты
****[#FFBBCC] Кредитный лимит не выдан
***[#FFBBCC] Экран КК не открывался
**[#FFBBCC] После приложение не открывалось
**[#lightgreen] Карта доставлена
**[#FFBBCC] Карта не может быть доставлена
@endmindmap
